body:
  - type: markdown
    attributes:
      value: |
        > [!CAUTION]
        > You MUST NOT enter any information from the ONS SRS which has not been cleared for release by the ONS SRS output checking team.

        > [!IMPORTANT]
        > Ensure you ask only one question per discussion. But feel free to start as many Q&A discussions as you need.

        > [!TIP]
        > You may find your answer more quickly by searching through previous Q&As.
  - type: textarea
    id: body
    attributes:
      label: Describe your question clearly
      placeholder: "Only one question per discussion"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Pre-submission checklist
      options:
        - label: You are sure you have not entered any information which has not been cleared for release by the ONS SRS output checking team?
          required: true
        - label: You have asked only one question in the textbox above?
          required: true
        - label: You have checked answers to similar questions in existing Q&As?
          required: true

